/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webbrowser.model;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import webbrowser.ConectDatabase.FazConsulta;
import webbrowser.ConectDatabase.ListaConsulta;
import webbrowser.gui.plataforma;

/**
 *
 * @author andre
 */
public class TabFavorito extends javax.swing.JPanel {

    private Object displayEditorPane;
    FavoritoTableModel FavoritoTable = new FavoritoTableModel();
    //ClsSQLHistorico cls = new ClsSQLHistorico();

    public TabFavorito() throws SQLException {
        initComponents();
        jTableFavorito.setModel(FavoritoTable);
        carrega();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLimpaTudo = new javax.swing.JButton();
        jButtonFecharAba = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFavorito = new javax.swing.JTable();
        jButtonExcluiSelecionado = new javax.swing.JButton();

        jButtonLimpaTudo.setText("Limpar tudo");
        jButtonLimpaTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaTudoActionPerformed(evt);
            }
        });

        jButtonFecharAba.setText("Fechar");
        jButtonFecharAba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFecharAbaMouseClicked(evt);
            }
        });
        jButtonFecharAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAbaActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(jPanel1.getPreferredSize());

        jTableFavorito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFavorito.setMaximumSize(new java.awt.Dimension(800, 680));
        jTableFavorito.setMinimumSize(new java.awt.Dimension(400, 300));
        jTableFavorito.setPreferredSize(jPanel1.getMaximumSize());
        jTableFavorito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFavoritoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFavorito);

        jButtonExcluiSelecionado.setText("Excluir Selecionado");
        jButtonExcluiSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFecharAba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(jButtonExcluiSelecionado)
                        .addGap(141, 141, 141)
                        .addComponent(jButtonLimpaTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpaTudo)
                    .addComponent(jButtonFecharAba)
                    .addComponent(jButtonExcluiSelecionado)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpaTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaTudoActionPerformed
        try {
            for (int i = 0; i < ListaConsulta.aListFavorito.size(); i++) {
                Historico h = new Historico();
                h.RemoveFavoritoTodos(webbrowser.Classes.UsuarioLogado.getUsuarioLogado());
                FavoritoTable.DeleteAllRowsInTable();
                carrega();
            }
        } catch (Exception ex) {
            Logger.getLogger(TabFavorito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLimpaTudoActionPerformed

    private void jButtonExcluiSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiSelecionadoActionPerformed

        try {
            Historico x = new Historico();
            String h;
            h = FavoritoTable.getColunaSelecionada(jTableFavorito.getSelectedRow());
            x.RemoveFavoritoSelecionado(h, webbrowser.Classes.UsuarioLogado.getUsuarioLogado());
            FavoritoTable.DeleteRowInTable(h);
            carrega();
        } catch (Exception ex) {
            Logger.getLogger(TabFavorito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExcluiSelecionadoActionPerformed

    private void jButtonFecharAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAbaActionPerformed
        plataforma p = new plataforma();
        p.RemoveSelectedTab(TabFavorito.this.getX(), TabFavorito.this.getY());

    }//GEN-LAST:event_jButtonFecharAbaActionPerformed

    private void jButtonFecharAbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharAbaMouseClicked

    }//GEN-LAST:event_jButtonFecharAbaMouseClicked

    private void jTableFavoritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFavoritoMouseClicked
        if (evt.getClickCount() == 2) {
            String urlPassada = "" + FavoritoTable.getValueAt(jTableFavorito.getSelectedRow(), 0);
            webbrowser.Classes.urlClicada.setUrlClicada(urlPassada);
            System.out.println(webbrowser.Classes.urlClicada.getUrlClicada());

            webbrowser.gui.plataforma.carregaTAbComLink();
            
        }
    }//GEN-LAST:event_jTableFavoritoMouseClicked

    //carrega dados na tabela
    public void carrega() {
        FazConsulta f = new FazConsulta();

        try {
            f.fazConsultaFavoritoSQL("select distinct UrlAcesso from historico where usuarioAcesso = '"
                    + webbrowser.Classes.UsuarioLogado.getUsuarioLogado()
                    + "' and favoritoAcesso = true");
        } catch (SQLException ex) {
            Logger.getLogger(TabFavorito.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (jTableFavorito.getRowCount() > 0) {
            System.out.println("tem linhas");
            FavoritoTable.DeleteAllRowsInTable();
        }

        for (String aList : ListaConsulta.aListFavorito) {
            FavoritoTable.addRowInTable(aList.toString());
        }
    }

    public void apaga() {

        if (jTableFavorito.getRowCount() > 0) {
            do {
                ((DefaultTableModel) jTableFavorito.getModel()).removeRow(0);
            } while (jTableFavorito.getRowCount() > 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluiSelecionado;
    private javax.swing.JButton jButtonFecharAba;
    private javax.swing.JButton jButtonLimpaTudo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFavorito;
    // End of variables declaration//GEN-END:variables
}
