/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webbrowser.model;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import webbrowser.Classes.UsuarioLogado;
import webbrowser.ConectDatabase.ClsSQLHistorico;
import webbrowser.ConectDatabase.FazConsulta;
import webbrowser.ConectDatabase.ListaConsulta;
import webbrowser.gui.plataforma;

/**
 *
 * @author andre
 */
public class TabHistorico extends javax.swing.JPanel {

    private Object displayEditorPane;
    HistoricoTableModel HistoricoTable = new HistoricoTableModel();
    //ClsSQLHistorico cls = new ClsSQLHistorico();

    public TabHistorico() throws SQLException {
        initComponents();
        jTableHistorico.setModel(HistoricoTable);
        carrega();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLimpaTudo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistorico = new javax.swing.JTable();
        jButtonExcluiSelecionado = new javax.swing.JButton();
        jTextFieldbuscaURL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscaURL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBuscaData = new javax.swing.JTextField();
        jButtonBuscaData = new javax.swing.JButton();
        jRadioButtonOrdemAlfabetica = new javax.swing.JRadioButton();
        jRadioButtonOrdemData = new javax.swing.JRadioButton();

        jButtonLimpaTudo.setText("Limpar tudo");
        jButtonLimpaTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaTudoActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(jPanel1.getPreferredSize());

        jTableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHistorico.setMaximumSize(new java.awt.Dimension(800, 680));
        jTableHistorico.setMinimumSize(new java.awt.Dimension(400, 300));
        jTableHistorico.setPreferredSize(jPanel1.getMaximumSize());
        jTableHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHistoricoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHistorico);

        jButtonExcluiSelecionado.setText("Excluir Selecionado");
        jButtonExcluiSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiSelecionadoActionPerformed(evt);
            }
        });

        jTextFieldbuscaURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldbuscaURLFocusGained(evt);
            }
        });
        jTextFieldbuscaURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbuscaURLActionPerformed(evt);
            }
        });
        jTextFieldbuscaURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldbuscaURLKeyPressed(evt);
            }
        });

        jLabel1.setText("Pesquisa URL:");

        jButtonBuscaURL.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonBuscaURL.setText("Busca");
        jButtonBuscaURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaURLActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisa Data:");

        jTextFieldBuscaData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBuscaDataFocusGained(evt);
            }
        });
        jTextFieldBuscaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaDataActionPerformed(evt);
            }
        });
        jTextFieldBuscaData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaDataKeyPressed(evt);
            }
        });

        jButtonBuscaData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonBuscaData.setText("Busca");
        jButtonBuscaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaDataActionPerformed(evt);
            }
        });

        jRadioButtonOrdemAlfabetica.setText("Ordem Alfabetica");
        jRadioButtonOrdemAlfabetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdemAlfabeticaActionPerformed(evt);
            }
        });

        jRadioButtonOrdemData.setText("Ordem de Data");
        jRadioButtonOrdemData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdemDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldbuscaURL, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBuscaURL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonOrdemAlfabetica))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBuscaData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluiSelecionado)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLimpaTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonOrdemData))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldbuscaURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaURL)
                    .addComponent(jRadioButtonOrdemAlfabetica)
                    .addComponent(jRadioButtonOrdemData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaData)
                    .addComponent(jButtonExcluiSelecionado)
                    .addComponent(jButtonLimpaTudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpaTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaTudoActionPerformed
        try {
            for (int i = 0; i < ListaConsulta.aListHistorico.size(); i++) {
                Historico h = new Historico();
                h = ListaConsulta.aListHistorico.get(i);
                webbrowser.ConectDatabase.ClsSQLHistorico cls = new ClsSQLHistorico();
                cls.Excluir(h);
                HistoricoTable.DeleteRowInTable(h);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLimpaTudoActionPerformed

    private void jButtonExcluiSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiSelecionadoActionPerformed

        try {
            Historico h = new Historico();
            h = HistoricoTable.getColunaSelecionada(jTableHistorico.getSelectedRow());
            webbrowser.ConectDatabase.ClsSQLHistorico cls = new ClsSQLHistorico();
            cls.Excluir(h);
            HistoricoTable.DeleteRowInTable(h);
        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExcluiSelecionadoActionPerformed

    private void jButtonBuscaURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaURLActionPerformed

        FazConsulta f = new FazConsulta();
        String urlBuscada = jTextFieldbuscaURL.getText();
        String usuario = UsuarioLogado.getUsuarioLogado();
        String Sql = ("select * from historico where urlAcesso like '%" + urlBuscada + "%' and usuarioAcesso = '"
                + usuario + "'");
        try {
            f.fazConsultaSQL(Sql);
            HistoricoTable.DeleteAllRowsInTable();

        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Historico aList : ListaConsulta.aListHistorico) {
            HistoricoTable.addRowInTable(aList);
        }
    }//GEN-LAST:event_jButtonBuscaURLActionPerformed

    private void jTextFieldbuscaURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbuscaURLActionPerformed

    }//GEN-LAST:event_jTextFieldbuscaURLActionPerformed

    private void jTextFieldBuscaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaDataActionPerformed

        FazConsulta f = new FazConsulta();
        String dataBuscada = jTextFieldBuscaData.getText();
        String usuario = UsuarioLogado.getUsuarioLogado();
        String Sql = ("select * from historico where dataAcesso like '%" + dataBuscada + "%' and usuarioAcesso = '"
                + usuario + "'");
        System.out.println(Sql);
        try {
            f.fazConsultaSQL(Sql);
            HistoricoTable.DeleteAllRowsInTable();

        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Historico aList : ListaConsulta.aListHistorico) {
            HistoricoTable.addRowInTable(aList);
        }
    }//GEN-LAST:event_jTextFieldBuscaDataActionPerformed

    private void jButtonBuscaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaDataActionPerformed
        FazConsulta f = new FazConsulta();
        String dataBuscada = jTextFieldBuscaData.getText();
        String usuario = UsuarioLogado.getUsuarioLogado();
        String Sql = ("select * from historico where dataAcesso like '%" + dataBuscada + "%' and usuarioAcesso = '"
                + usuario + "'");
        System.out.println(Sql);
        try {
            f.fazConsultaSQL(Sql);
            HistoricoTable.DeleteAllRowsInTable();

        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Historico aList : ListaConsulta.aListHistorico) {
            HistoricoTable.addRowInTable(aList);
        }
    }//GEN-LAST:event_jButtonBuscaDataActionPerformed

    private void jRadioButtonOrdemAlfabeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdemAlfabeticaActionPerformed
        if (jRadioButtonOrdemAlfabetica.isSelected()) {
            jRadioButtonOrdemData.setSelected(false);
            carregaAlfabetico();
            //System.err.println("carregou");
            //jRadioButtonOrdemAlfabetica.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonOrdemAlfabeticaActionPerformed

    private void jRadioButtonOrdemDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdemDataActionPerformed
        //jRadioButtonOrdemData.setSelected(true);
        if (jRadioButtonOrdemData.isSelected()) {
            jRadioButtonOrdemAlfabetica.setSelected(false);
            carrega();
            //System.err.println("carregou");
            //jRadioButtonOrdemData.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonOrdemDataActionPerformed

    private void jTextFieldbuscaURLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldbuscaURLKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonBuscaURL.doClick();
        }
    }//GEN-LAST:event_jTextFieldbuscaURLKeyPressed

    private void jTextFieldBuscaDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaDataKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonBuscaData.doClick();
        }
    }//GEN-LAST:event_jTextFieldBuscaDataKeyPressed

    private void jTextFieldbuscaURLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldbuscaURLFocusGained
        jTextFieldBuscaData.setText(null);
    }//GEN-LAST:event_jTextFieldbuscaURLFocusGained

    private void jTextFieldBuscaDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscaDataFocusGained
        jTextFieldbuscaURL.setText(null);
    }//GEN-LAST:event_jTextFieldBuscaDataFocusGained

    private void jTableHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHistoricoMouseClicked
        if (evt.getClickCount() == 2) {
            String urlPassada = "" + HistoricoTable.getValueAt(jTableHistorico.getSelectedRow(), 0);
            //String urlPassada = HistoricoTable.getValueAt(jTableHistorico.getSelectedRow(), 0).toString();

            webbrowser.Classes.urlClicada.setUrlClicada(urlPassada);
            System.out.println(webbrowser.Classes.urlClicada.getUrlClicada());

            webbrowser.gui.plataforma.carregaTAbComLink();

        }

//            Historico h = new Historico();
//            h = HistoricoTable.getColunaSelecionada(1);
//            String abrirUrl;// = h.getUrlAcesso();
//            abrirUrl = HistoricoTable.getValueAt(jTableHistorico.getSelectedRow(), 0).toString();
//            System.out.println(abrirUrl);
//            webbrowser.Classes.urlClicada.setUrlClicada(abrirUrl);
//            tabLink t = new tabLink();
//            plataforma p = new plataforma();
//            p.createTabPanel(jPanel1, WIDTH);
//            p.createTabPanel(t, p.visibleTabPanels.size() - 1);
//            jTabbedPane1.setSelectedIndex(visibleTabPanels.size() - 1);
//            webbrowser.gui.plataforma.class.getMethod(createTabPanel, t, visibleTabPanels.size() - 1);
//            p.carregaTAbComLink();
//       }
    }//GEN-LAST:event_jTableHistoricoMouseClicked

    //carrega dados na tabela
    public void carrega() {
        FazConsulta f = new FazConsulta();
        try {
            f.fazConsultaSQL("select * from historico where  usuarioAcesso = '"
                    + webbrowser.Classes.UsuarioLogado.getUsuarioLogado()
                    + "'");
        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (jTableHistorico.getRowCount() > 0) {
            System.out.println("tem linhas");
            HistoricoTable.DeleteAllRowsInTable();
        }
        for (Historico aList : ListaConsulta.aListHistorico) {
            HistoricoTable.addRowInTable(aList);
        }
    }

    public void carregaAlfabetico() {
        FazConsulta f = new FazConsulta();
        try {
            f.fazConsultaSQL("select * from historico where  usuarioAcesso = '"
                    + webbrowser.Classes.UsuarioLogado.getUsuarioLogado()
                    + "'" + "order by urlAcesso");
        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (jTableHistorico.getRowCount() > 0) {
            System.out.println("tem linhas");
            HistoricoTable.DeleteAllRowsInTable();
        }
        for (Historico aList : ListaConsulta.aListHistorico) {
            HistoricoTable.addRowInTable(aList);
        }
    }

    public void carregaData() {
        FazConsulta f = new FazConsulta();
        try {
            f.fazConsultaSQL("select * from historico where  usuarioAcesso = '"
                    + webbrowser.Classes.UsuarioLogado.getUsuarioLogado()
                    + "'" + "order by dataAcesso");
        } catch (SQLException ex) {
            Logger.getLogger(TabHistorico.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (jTableHistorico.getRowCount() > 0) {
            System.out.println("tem linhas");
            HistoricoTable.DeleteAllRowsInTable();
        }
        for (Historico aList : ListaConsulta.aListHistorico) {
            HistoricoTable.addRowInTable(aList);
        }
    }

    public void apaga() {

        if (jTableHistorico.getRowCount() > 0) {
            do {
                ((DefaultTableModel) jTableHistorico.getModel()).removeRow(0);
            } while (jTableHistorico.getRowCount() > 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscaData;
    private javax.swing.JButton jButtonBuscaURL;
    private javax.swing.JButton jButtonExcluiSelecionado;
    private javax.swing.JButton jButtonLimpaTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonOrdemAlfabetica;
    private javax.swing.JRadioButton jRadioButtonOrdemData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHistorico;
    private javax.swing.JTextField jTextFieldBuscaData;
    private javax.swing.JTextField jTextFieldbuscaURL;
    // End of variables declaration//GEN-END:variables
}
