/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webbrowser.model;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Stack;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import java.sql.PreparedStatement;
import static javax.swing.JOptionPane.showMessageDialog;
import static webbrowser.model.tab.UrlDigitada;

/**
 *
 * @author andre
 */
public class tabLink extends javax.swing.JPanel {

    public tabLink() {
        initComponents();
        jTextFieldUrl.setText(webbrowser.Classes.urlClicada.getUrlClicada());
        jButtonGo.doClick();
    }
    boolean privado = false;
    Historico his = new Historico();
    Date agora = new Date();
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
    Stack<String> anterior = new Stack<>();
    Stack<String> posterior = new Stack<>();
    String atual = "";
    public static String UrlDigitada = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jButtonForward = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jTextFieldUrl = new javax.swing.JTextField();
        jButtonGo = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        anonimo = new javax.swing.JRadioButton();
        botaoFavorito = new javax.swing.JRadioButton();

        jButtonBack.setText("<");
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jButtonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonBackKeyPressed(evt);
            }
        });

        jButtonForward.setText(">");
        jButtonForward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonForwardMouseClicked(evt);
            }
        });
        jButtonForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardActionPerformed(evt);
            }
        });
        jButtonForward.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonForwardKeyPressed(evt);
            }
        });

        jButtonStop.setText("X");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jTextFieldUrl.setText("https://");
        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jTextFieldUrl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUrlKeyPressed(evt);
            }
        });

        jButtonGo.setText("Vai");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("F5");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jButtonRefresh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonRefreshKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        anonimo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        anonimo.setText("Aba Incógnita");
        anonimo.setActionCommand("anonimo");
        anonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anonimoActionPerformed(evt);
            }
        });

        botaoFavorito.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botaoFavorito.setText("Favorito");
        botaoFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFavoritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonForward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefresh)
                        .addGap(6, 6, 6)
                        .addComponent(botaoFavorito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonForward)
                    .addComponent(jButtonStop)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGo)
                    .addComponent(jButtonRefresh)
                    .addComponent(anonimo)
                    .addComponent(botaoFavorito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        jButtonGo.setMnemonic(KeyEvent.VK_ENTER);
        UrlDigitada = jTextFieldUrl.getText();
        JEditorPane jep = new JEditorPane();

        //pilha de enderecos
        if (atual == null) {
            atual = "" + UrlDigitada;
        } else {
            anterior.push(atual);
            atual = "" + UrlDigitada;
            // posterior.clear();    
        }

        if (!anonimo.isSelected()) { //verifica se aba está anonima - balbinot
            System.out.println("Abriu normal");
            String data = df.format(agora);
            String urlDigitada = UrlDigitada;
            String usuarioLogado = webbrowser.Classes.UsuarioLogado.getUsuarioLogado();
            boolean favorito = false;
            PreparedStatement stmt = null;
            String sql = "select favoritoAcesso from historico where "
                    + "(urlAcesso = "
                    + urlDigitada
                    + " and usuarioAcesso = "
                    + usuarioLogado + ")";
            try {
                his.salvaNoHistorico(data, urlDigitada, usuarioLogado, favorito);
            } catch (NullPointerException ex) {
                showMessageDialog(null, "Null:o URL digitado" + urlDigitada + " não é valido");

            } catch (RuntimeException ex) {
                showMessageDialog(null, "Runtime:o URL digitado" + urlDigitada + " não é valido");

            }

            //ResultSet resultado = stmt.executeQuery();
            //int res = resultado.getInt(1);
            //System.out.println(resultado);
            //if (res == 1) {
            //    favorito = true;
            //    botaoFavorito.setSelected(true);
            //}    
            //System.out.println(data);
            //System.out.println(urlDigitada);
            //System.out.println(usuarioLogado);
            //System.out.println(favorito);
            //his.salvaNoHistorico(data, urlDigitada, usuarioLogado, favorito);
        } else {
            System.out.println("Abriu anonimo");
        }
        //JEditorPane jep = jEditorPane1;
        jep.setEditable(false);
        String conteudo = "conteudo aqui";

        try {
//            URL url = new URL(UrlDigitada);
//            URI uri = url.toURI();
//            BufferedReader br = new BufferedReader(new InputStreamReader(url.openStream()));
//            String s;
//            String conteudoBaixado;
//            conteudoBaixado = "";
//            
//            while ((s = br.readLine()) != null) {
//                conteudoBaixado = "" + conteudoBaixado + "\n" + s;
//                boolean isTag = false;
//                String linha = br.readLine();
//                String linhaImp = "";
//                String tag = "";
//                for (int cont = 0; cont < linha.length(); cont++) {
//                    char letra = linha.charAt(cont);
//                    if (letra == '<') {
//                        isTag = true;
//                    }
//                    if (!isTag) {
//                        linhaImp += letra;
//                    }
//                    if (isTag) {
//                        tag += letra;
//                    }
//                    if (letra == '>') {
//                        isTag = false;
//                    }
//                }
//                if (!linhaImp.equals("")) {
//                    //tag = tag.replace(" ","");
//                    if (tag.equals("<h4></h4>")) {
//                        //System.out.println("Troca Tag");
//                    }
//                    //System.out.println(tag);
//                    //System.out.println(linhaImp);
//                }
//            }
//            System.out.println(conteudoBaixado);
            jep.setPage(UrlDigitada);

//           jep.setPage(conteudoBaixado);
//           br.close();
            //aqui conteudo que deve ser debugadi em linhas - jep.add(conteudo);
        } catch (IOException e) {
            jep.setContentType("text/html");
            showMessageDialog(null, "<html>Não pode abria pagina " + jTextFieldUrl.getText() + "  </html>");
            //jep.setText("<html>Não pode abria pagina " + jTextFieldUrl.getText() + "  </html>");
//        } catch (URISyntaxException ex) {
//            Logger.getLogger(tab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RuntimeException ex) {
            showMessageDialog(null, "<html>Não pode abria pagina " + jTextFieldUrl.getText() + "  </html>");

        }
        JScrollPane scrollPane = new JScrollPane(jep);
        //f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(scrollPane, BorderLayout.CENTER);
        jPanel2.setSize(512, 342);
        jPanel2.show();

    }//GEN-LAST:event_jButtonGoActionPerformed

    public static String getUrlDigitada() {
        return UrlDigitada;
    }


    private void jTextFieldUrlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUrlKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonGo.doClick();
        }
    }//GEN-LAST:event_jTextFieldUrlKeyPressed

    private void jButtonRefreshKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonRefreshKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            jButtonRefresh.doClick();
        }
    }//GEN-LAST:event_jButtonRefreshKeyPressed

    private void jButtonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBackKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackKeyPressed

    private void jButtonForwardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonForwardKeyPressed

    }//GEN-LAST:event_jButtonForwardKeyPressed

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        if (anterior.isEmpty()) {
            System.out.println("anterior vazia");
        } else {
            posterior.push(atual);
            atual = anterior.pop();
            jTextFieldUrl.setText(atual);
            jButtonGo.doClick();
        }
    }//GEN-LAST:event_jButtonBackMouseClicked

    private void jButtonForwardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForwardMouseClicked
        if (posterior.isEmpty()) {
            System.out.println("posterior vazia");
        } else {
            anterior.push(atual);
            atual = posterior.pop();
            jTextFieldUrl.setText(atual);
            jButtonGo.doClick();
        }
    }//GEN-LAST:event_jButtonForwardMouseClicked

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        jButtonRefresh.setMnemonic(KeyEvent.VK_F5);
        String UrlDigitada = jTextFieldUrl.getText();
        JEditorPane jep = new JEditorPane();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void anonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anonimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anonimoActionPerformed

    private void botaoFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFavoritoActionPerformed
        // TODO add your handling code here:
        if (botaoFavorito.isSelected()) {
            if (webbrowser.Classes.UsuarioLogado.getUsuarioLogado().equals("default")) {
                showMessageDialog(null, "Você precisa estar Logado para Favoritar URL's");
                jButtonGo.doClick();
                botaoFavorito.setSelected(false);
            } else {
                jButtonGo.doClick();
                String data = df.format(agora);
                String urlDigitada = UrlDigitada;
                String usuarioLogado = webbrowser.Classes.UsuarioLogado.getUsuarioLogado();
                boolean favorito = true;
                his.salvaFavorito(data, urlDigitada, usuarioLogado, favorito);
                botaoFavorito.setSelected(false);
            }
        }
    }//GEN-LAST:event_botaoFavoritoActionPerformed

    private void jButtonForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonForwardActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    public final void setModel(JComboBox _comboBox, List<String> _browser) {
        _comboBox.setModel(
                new javax.swing.DefaultComboBoxModel(
                        _browser.toArray(new String[_browser.size()])));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anonimo;
    private javax.swing.JRadioButton botaoFavorito;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonForward;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables

}
